### ISSUE TITLE
failed to read dockerfile: open Dockerfile-gpu: no such file or directory

### ISSUE THREAD

**Issue by bunkerman** [rishikanthc/Scriberr#105]
I'm getting this error when docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
```
WARN[0000] current commit information was not captured by the build  error="failed to read current commit information with git rev-parse --is-inside-work-tree"
failed to solve: failed to read dockerfile: open Dockerfile-gpu: no such file or directory
```

I changed the compose file to:

```
services:
  app1:
    image: ghcr.io/rishikanthc/scriberr:${IMAGE_TAG:-main}
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
      # No args needed as environment variables are passed at runtime
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./scriberr_data:/scriberr
    restart: unless-stopped
```

I'm using a separate postgres container and inserted the info in  the .env file

Can I also delete the arm64 platfform in the compose file?

and is there also a main-cuda-12 image?

Is the building necassary or do you provide pre built images?
