### ISSUE TITLE
Transription fail; diarization not downloaded

### ISSUE THREAD

**Issue by danielholm** [rishikanthc/Scriberr#121]
Hi,

I've been trying to get this service to work the past weeks, and so unsuccessfully. First issues with cuda drivers,  and so on.

Now, I get the service to start, I see the webui and am able to upload my files. The transcription however always fail. The docker logs presents with few reasons why. However the download of diarization fails. And the transcription fails while diarization is either on or off.

**.env:**

```
# Docker image configuration
IMAGE_TAG=main # Docker image tag to use for building the Docker image
PORT=3033 # Port to use for running the web interface
HOST_PORT=3033

# Database configuration
POSTGRES_PORT=5432 # Port to use for PostgreSQL database
POSTGRES_USER=root # Username for PostgreSQL database
POSTGRES_PASSWORD=redacted # Password for PostgreSQL database
POSTGRES_HOST=db # Hostname for PostgreSQL database
POSTGRES_DB=local # Database name

# Made using the variables from above. Will be removed in later versions.
# DATABASE_URL=postgres://root:mysecretpassword@db:5432/local # Database URL for connection to PostgreSQL database with credentials from above

# Application configuration
ADMIN_USERNAME=red # Username for admin user in web interface
ADMIN_PASSWORD=redacted # Password for admin user in web interface

# AI configuration
# Default Model to use for transcription, can be set to any OpenAI model or Ollama model
# For ollama connections, enter the model name and version number. EG: llama3.2:latest
AI_MODEL="gemma3:4b"
# Leave blank to use default (OpenAI API), otherwise set to the base URL of your OpenAI API compatible server
# For ollama connections, enter the IP of the Ollama server, and then the port it is running on.
# Include the /v1/ or /api/v1/ path if needed (OpenWeb UI uses /api/ and ollama uses /v1/
# Example: http://192.168.1.5:11434 or http://host.docker.internal:11434
# NOTE: host.docker.internal is only available on Windows and MacOS, use the IP address of the host machine on Linux
# NOTE: localhost and 127.0.0.1 will not work, as they refer to the container itself, not the host machine
OLLAMA_BASE_URL="http://IP:11434/v1"

# API Keys
# NOTE:
# If using Ollama, you can leave these blank or set to a dummy value
# If using OpenAI, you must set these to your API keys
# If using a custom API compatible server, you must set these to your API keys
OPENAI_API_KEY="ollama" # Needed for retrieving models from OpenAI, for Ollama connections, this can be left blank or set to a dummy value

# Diarization configuration
# Default Model to use for Diarization, can be set to any compatible model that supports diarization
# NOTE: This model will be downloaded automatically if it is not already present in the models directory
# NOTE: You MUST provide a valid HuggingFace API token with access to pyannote/speaker-diarization models
DIARIZATION_MODEL=pyannote/speaker-diarization
#pyannote/speaker-diarization@3.1 #does not work
#pyannote/speaker-diarization@3.0 #does not work 
HUGGINGFACE_TOKEN="hf_redActed" # Required for accessing speaker diarization models from HuggingFace

# Paths
# These almost never need to be changed. They are the paths to the directories where the models and audio files are stored
MODELS_DIR=/scriberr/models
WORK_DIR=/scriberr/temp
AUDIO_DIR=/scriberr/uploads

# Server configuration
BODY_SIZE_LIMIT=1G
HARDWARE_ACCEL=gpu # Set to 'gpu' if you have a Nvidia GPU
USE_WORKER=true # Enable background processing of transcription jobs
WHISPER_BATCH_SIZE=1

# TEsts
LANGUAGE=sv
WHISPER_model=medium
COMPUTE_TYPE=float32

```

**docker-compose.yaml:**
```
services:
  app:
    image: ghcr.io/rishikanthc/scriberr:${IMAGE_TAG:-main}
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
      # No args needed as environment variables are passed at runtime
    env_file:
      - .env
    environment:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - scriberr_data:/scriberr
    networks:
      - app-network
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
     interval: 30s
     timeout: 10s
     retries: 5
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #ports:
     # - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  scriberr_data:
```

**docker-compose.gpu.yaml:**
```
# This can be added when running the main docker-compose.yml file to add gpu support
# add this in your command line: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-cuda128
    # You can find your architecture by running: nvidia-smi if on linux
    # You can find your architecture by running: system_profiler SPDisplaysDataType if on mac
    # You can find your architecture by running: wmic path win32_videocontroller get name if on windows
    # You will need to change the image to match your architecture, E.G. "main-cuda-11"
    image: ghcr.io/rishikanthc/scriberr:main-cuda128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
Logs:

> app-1  | Failed to download diarization model: Error: Command failed: python /app/whisper/download_diarize.py
> app-1  | Traceback (most recent call last):
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
> app-1  |     response.raise_for_status()
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
> app-1  |     raise HTTPError(http_error_msg, response=self)
> app-1  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/3.0/config.yaml
> app-1  | 
> app-1  | The above exception was the direct cause of the following exception:
> app-1  | 
> app-1  | Traceback (most recent call last):
> app-1  |   File "/app/whisper/download_diarize.py", line 11, in <module>
> app-1  |     pipeline = Pipeline.from_pretrained(
> app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py", line 90, in from_pretrained
> app-1  |     config_yml = hf_hub_download(
> app-1  |                  ^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
> app-1  |     return fn(*args, **kwargs)
> app-1  |            ^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 961, in hf_hub_download
> app-1  |     return _hf_hub_download_to_cache_dir(
> app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1024, in _hf_hub_download_to_cache_dir
> app-1  |     (url_to_download, etag, commit_hash, expected_size, xet_file_data, head_call_error) = _get_metadata_or_catch_error(
> app-1  |                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1484, in _get_metadata_or_catch_error
> app-1  |     metadata = get_hf_file_metadata(
> app-1  |                ^^^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
> app-1  |     return fn(*args, **kwargs)
> app-1  |            ^^^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1401, in get_hf_file_metadata
> app-1  |     r = _request_wrapper(
> app-1  |         ^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 285, in _request_wrapper
> app-1  |     response = _request_wrapper(
> app-1  |                ^^^^^^^^^^^^^^^^^
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 309, in _request_wrapper
> app-1  |     hf_raise_for_status(response)
> app-1  |   File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 416, in hf_raise_for_status
> app-1  |     raise _format(RevisionNotFoundError, message, response) from e
> app-1  | huggingface_hub.errors.RevisionNotFoundError: 404 Client Error. (Request ID: Root=1-681b1b8d-0e3da86909feba663f989780;eb3657f0-5295-452e-9afc-f9b41f822849)
> app-1  | 
> app-1  | Revision Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/3.0/config.yaml.
> app-1  | Invalid rev id: 3.0
> app-1  | 
> app-1  |     at genericNodeError (node:internal/errors:983:15)
> app-1  |     at wrappedFn (node:internal/errors:537:14)
> app-1  |     at ChildProcess.exithandler (node:child_process:414:12)
> app-1  |     at ChildProcess.emit (node:events:507:28)
> app-1  |     at maybeClose (node:internal/child_process:1101:16)
> app-1  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
> app-1  |   code: 1,
> app-1  |   killed: false,
> app-1  |   signal: null,
> app-1  |   cmd: 'python /app/whisper/download_diarize.py',
> app-1  |   stdout: '',
> app-1  |   stderr: 'Traceback (most recent call last):\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status\n' +
> app-1  |     '    response.raise_for_status()\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status\n' +
> app-1  |     '    raise HTTPError(http_error_msg, response=self)\n' +
> app-1  |     'requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/3.0/config.yaml\n' +
> app-1  |     '\n' +
> app-1  |     'The above exception was the direct cause of the following exception:\n' +
> app-1  |     '\n' +
> app-1  |     'Traceback (most recent call last):\n' +
> app-1  |     '  File "/app/whisper/download_diarize.py", line 11, in <module>\n' +
> app-1  |     '    pipeline = Pipeline.from_pretrained(\n' +
> app-1  |     '               ^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py", line 90, in from_pretrained\n' +
> app-1  |     '    config_yml = hf_hub_download(\n' +
> app-1  |     '                 ^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn\n' +
> app-1  |     '    return fn(*args, **kwargs)\n' +
> app-1  |     '           ^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 961, in hf_hub_download\n' +
> app-1  |     '    return _hf_hub_download_to_cache_dir(\n' +
> app-1  |     '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1024, in _hf_hub_download_to_cache_dir\n' +
> app-1  |     '    (url_to_download, etag, commit_hash, expected_size, xet_file_data, head_call_error) = _get_metadata_or_catch_error(\n' +
> app-1  |     '                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1484, in _get_metadata_or_catch_error\n' +
> app-1  |     '    metadata = get_hf_file_metadata(\n' +
> app-1  |     '               ^^^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn\n' +
> app-1  |     '    return fn(*args, **kwargs)\n' +
> app-1  |     '           ^^^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1401, in get_hf_file_metadata\n' +
> app-1  |     '    r = _request_wrapper(\n' +
> app-1  |     '        ^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 285, in _request_wrapper\n' +
> app-1  |     '    response = _request_wrapper(\n' +
> app-1  |     '               ^^^^^^^^^^^^^^^^^\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 309, in _request_wrapper\n' +
> app-1  |     '    hf_raise_for_status(response)\n' +
> app-1  |     '  File "/scriberr/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 416, in hf_raise_for_status\n' +
> app-1  |     '    raise _format(RevisionNotFoundError, message, response) from e\n' +
> app-1  |     'huggingface_hub.errors.RevisionNotFoundError: 404 Client Error. (Request ID: Root=1-681b1b8d-0e3da86909feba663f989780;eb3657f0-5295-452e-9afc-f9b41f822849)\n' +
> app-1  |     '\n' +
> app-1  |     'Revision Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/3.0/config.yaml.\n' +
> app-1  |     'Invalid rev id: 3.0\n'
> app-1  | }
> app-1  | [Hooks] Incoming request: {
> app-1  |   path: '/health',
> app-1  |   method: 'GET',
> app-1  |   origin: null,
> app-1  |   host: 'localhost:3000',
> app-1  |   referer: null
> app-1  | }
> app-1  | [Hooks] Request origin: null
> app-1  | [Hooks] Unauthenticated request to protected path: /health
> app-1  | [Hooks] Incoming request: {
> app-1  |   path: '/health',
> app-1  |   method: 'GET',
> app-1  |   origin: null,
> app-1  |   host: 'localhost:3000',
> app-1  |   referer: null
> app-1  | }
> app-1  | [Hooks] Request origin: null
> app-1  | [Hooks] Unauthenticated request to protected path: /health
> app-1  | [Hooks] Incoming request: {
> app-1  |   path: '/health',
> app-1  |   method: 'GET',
> app-1  |   origin: null,
> app-1  |   host: 'localhost:3000',
> app-1  |   referer: null
> app-1  | }
> app-1  | [Hooks] Request origin: null
> app-1  | [Hooks] Unauthenticated request to protected path: /health
> app-1  | [Hooks] Incoming request: {
> app-1  |   path: '/health',
> app-1  |   method: 'GET',
> app-1  |   origin: null,
> app-1  |   host: 'localhost:3000',
> app-1  |   referer: null
> app-1  | }
> app-1  | [Hooks] Request origin: null
> app-1  | [Hooks] Unauthenticated request to protected path: /health
