### ISSUE TITLE
Error with Docker instance: Upload failed: Unauthorized

### ISSUE THREAD

**Issue by ballerbude** [rishikanthc/Scriberr#74]
Hello dear friends,

I have a running instance using docker compose.

**Here is my docker-compose.yml:**

```
services:
  app:
    image: ghcr.io/rishikanthc/scriberr:${IMAGE_TAG:-main}
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
      args: # Build-time variables
        - DATABASE_URL=postgres://root:redacted@db:5432/local
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=redacted
        - AI_MODEL="gpt-4o-mini"
        - OLLAMA_BASE_URL=""
        - MODELS_DIR="/scriberr/models"
        - WORK_DIR="/scriberr/temp"
        - AUDIO_DIR="/scriberr/uploads"
        - OPENAI_API_KEY=""
        - BODY_SIZE_LIMIT=100M
    env_file:
      # Specify your .env file here
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Comment out the following line if you want to use a local directory for Scriberr data storage
      - ./scriberr_data:/scriberr
      # Uncomment the following line if you want to use a local directory for data storage
      #- /path/to/scriberr_data:/scriberr
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # Comment out the following line if you want to use a local directory for PostgreSQL data storage
      - ./postgres_data:/var/lib/postgresql/data
      # Uncomment the following line if you want to use a local directory for data storage
      #- /path/to/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

# Comment out the following lines if you want to use a local directory for data storage
volumes:
  postgres_data:
  scriberr_data:
```

**Here is my .env:**

```
# .env file
# Docker image configuration
IMAGE_TAG=main # Docker image tag to use for building the Docker image
PORT=3000 # Port to use for running the web interface

# Database configuration
POSTGRES_PORT=5432 # Port to use for PostgreSQL database
POSTGRES_USER=root # Username for PostgreSQL database
POSTGRES_PASSWORD=redacted # Password for PostgreSQL database
POSTGRES_DB=local # Database name
DATABASE_URL=postgres://root:redacted@db:5432/local # Database URL for connection to PostgreSQL database with credentials from above

# Application configuration
ADMIN_USERNAME=admin # Username for admin user in web interface
ADMIN_PASSWORD=redacted # Password for admin user in web interface

# AI configuration
# Default Model to use for transcription, can be set to any OpenAI model or Ollama model
# For ollama connections, enter the model name and version number. EG: llama3.2:latest
AI_MODEL="gpt-3.5-turbo"

# Leave blank to use default (OpenAI API), otherwise set to the base URL of your OpenAI API compatible server
# For ollama connections, enter the IP of the Ollama server, and then the port it is running on.
# Include the /v1/ or /api/v1/ path if needed (OpenWeb UI uses /api/ and ollama uses /v1/
# Example: http://192.168.1.5:11434 or http://host.docker.internal:11434
# NOTE: host.docker.internal is only available on Windows and MacOS, use the IP address of the host machine on Linux
# NOTE: localhost and 127.0.0.1 will not work, as they refer to the container itself, not the host machine
OLLAMA_BASE_URL=""

# API Keys
# NOTE:
# If using Ollama, you can leave these blank or set to a dummy value
# If using OpenAI, you must set these to your API keys
# If using a custom API compatible server, you must set these to your API keys
OPENAI_API_KEY="" # Needed for retrieving models from OpenAI, for Ollama connections, this can be left blank or set to a dummy value
HF_API_KEY="" # Needed for retrieving models from HuggingFace for Diarization

# Diarization configuration
# Default Model to use for Diarization, can be set to any HuggingFace model that supports diarization
# NOTE: This model will be downloaded automatically if it is not already present in the models directory
# NOTE: You can use any model that supports diarization, but the default model is pyannote/speaker-diarization
# NOTE: You can find a list of models that support diarization here: https://huggingface.co/models?other=speaker-diarization
DIARIZATION_MODEL=pyannote/speaker-diarization

MODELS_DIR=/scriberr/models
WORK_DIR=/scriberr/temp
AUDIO_DIR=/scriberr/uploads

# Server configuration
BODY_SIZE_LIMIT=1G
HARDWARE_ACCEL=cpu # Set to 'gpu' if you have a Nvidia GPU
```

I have complete the installation and my instance is accessible on the port 3000 over http://localhost:3000/

When I go to recordings and try to upload an audio file, I get the error message "Upload failed: Unauthorized" in the web interface. 

Inside the thell of the running docker container, I get the following output:

```
app-1  | [Hooks] Incoming request: {
app-1  |   path: '/api/check-config',
app-1  |   method: 'GET',
app-1  |   origin: null,
app-1  |   host: '192.168.178.xxx:3000',
app-1  |   referer: 'http://192.168.178.xxx:3000/'
app-1  | }
app-1  | [Hooks] Request origin: null
app-1  | [Hooks] Incoming request: {
app-1  |   path: '/api/audio-files',
app-1  |   method: 'GET',
app-1  |   origin: null,
app-1  |   host: '192.168.178.xxx:3000',
app-1  |   referer: 'http://192.168.178.xxx:3000/'
app-1  | }
app-1  | [Hooks] Request origin: null
app-1  | [Hooks] Unauthenticated request to protected path: /api/audio-files
app-1  | [Hooks] Incoming request: {
app-1  |   path: '/api/upload',
app-1  |   method: 'POST',
app-1  |   origin: 'http://192.168.178.xxx:3000',
app-1  |   host: '192.168.178.xxx:3000',
app-1  |   referer: 'http://192.168.178.xxx:3000/'
app-1  | }
app-1  | [Hooks] Request origin: http://192.168.178.xxx:3000
app-1  | [Hooks] Unauthenticated request to protected path: /api/upload
```

What am I missing? Why isn't it working?
