### ISSUE TITLE
Transcription error: RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by AdamT20054** [rishikanthc/Scriberr#83]
Currently having an issue on the nightly build with Cuda. Using the Cuda128 image after the normal nightly-gpu build also fails but due to a different reason (fixed in a recent PR, but not built for nightly-gpu)

My compose.yaml is as follows:

```
services:
  app:
    image: ghcr.io/rishikanthc/scriberr:nightly-cuda128
    env_file:
      - stack.env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - scriberr_data:/scriberr
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped
volumes:
  postgres_data:
  scriberr_data:
  
networks:
  app-network:
    driver: bridge

```

I am using a local Ollama instance.

Logs:
```
Saved original file for playback: /scriberr/uploads/1741427414475-original.m4a
Transcription options being used: {
  modelSize: 'base',
  language: 'en',
  threads: 4,
  processors: 1,
  diarization: false
}
Diarization setting: false
Queue settings: { DATABASE_URL: true, USE_WORKER: false }
Queueing job for audioId: 2
Job queued successfully: null
Queued job: {
  audioFile: {
    id: 2,
    fileName: '1741427414475.wav',
    originalFileName: '1741427414475-original.m4a',
    originalFileType: 'm4a',
    duration: null,
    transcript: null,
    transcriptionStatus: 'pending',
    summary: null,
    summaryPrompt: null,
    summaryStatus: null,
    language: 'en',
    lastError: null,
      
    peaks: [
       -8886,  6380, -11751, 13849, -12063, 13713, -11985, 13512,
      -11583, 13443, -11808, 13336, -13078, 13063, -12361, 13026,
      -10800, 13133,  -7167, 11836,  -5385,  5859,  -2984,  4876,
       -4280,  4399,  -2816,  3430,  -2117,  2327,  -1981,  2218,
       -1473,  1547,  -1080,  1480,  -1053,  1131,   -926,  1208,
       -1012,  1179,   -731,   915,   -628,   904,   -712,  1175,
        -924,  1494,   -987,  1236,   -897,   809,   -497,   529,
        -291,   340,   -250,   208,   -187,   171,   -279,   150,
        -188,   230,   -165,   149,   -218,   172,   -168,   278,
        -157,   173,   -190,   183,   -219,   173,   -227,   173,
        -151,   227,   -238,   218,   -301,   204,   -257,   229,
        -238,   247,   -262,   222,   -226,   252,   -197,   232,
        -235,   242,   -214,   185,
      ... 289592 more items
    ],
    modelSize: 'base',
    threads: 4,
    title: '2025-02-03 12-12-02_Audio_1',
    processors: 1,
    diarization: false,
    transcriptionProgress: 0,
    uploadedAt: 2025-03-08T09:50:21.377Z,
    transcribedAt: null,
    summarizedAt: null,
    updatedAt: null
  }
}
Starting transcription for file ID: 2
Using audio file path: /scriberr/uploads/1741427414475.wav
Retrieved fileInfo for ID 2: {
  modelSize: 'base',
  language: 'en',
  threads: 4,
  processors: 1,
  diarization: false
}
Diarization setting from database: false
Transcribing audio file: /scriberr/uploads/1741427414475.wav
Checking if diarization should be enabled: false
Diarization is disabled.
Using device: cuda (HARDWARE_ACCEL=cuda)
Executing Python with args: [
  'transcribe.py',
  '--audio-file',
  '/scriberr/uploads/1741427414475.wav',
  '--model-size',
      
,
  '--output-file',
  '/scriberr/uploads/transcript-2.json',
  '--threads',
  '4',
  '--language',
  'en',
  '--device',
      
,
  '--compute-type',
  'float16'
]
[Hooks] Incoming request: {
  path: '/api/audio-files',
  method: 'GET',
  origin: null,
  host: '192.168.1.192:3000',
  referer: 'http://192.168.1.192:3000/'
}
[Hooks] Request origin: null
API AUDIO FILES ---->
API AUDIO FILES ----> finishing auth
Transcription error: INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
Transcription error: INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
[Hooks] Incoming request: {
  path: '/api/audio-files',
  method: 'GET',
  origin: null,
  host: '192.168.1.192:3000',
  referer: 'http://192.168.1.192:3000/'
}
[Hooks] Request origin: null
API AUDIO FILES ---->
API AUDIO FILES ----> finishing auth
Transcription error: Traceback (most recent call last):
  File "/app/transcribe.py", line 146, in <module>
Transcription error:     main()
  File "/app/transcribe.py", line 93, in main
Transcription error:     model = whisperx.load_model(
            ^^^^^^^^^^^^^^^^^^^^
Transcription error:   File "/scriberr/.venv/lib/python3.12/site-packages/whisperx/asr.py", line 325, in load_model
Transcription error:     model = model or WhisperModel(whisper_arch,
Transcription error:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scriberr/.venv/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 634, in __init__
Transcription error:     self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Transcription error: RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
Python process exited with code 1
Transcription failed: Error: Python process exited with code 1
    at ChildProcess.<anonymous> (file:///app/build/server/chunks/jobQueue-CjBJp1X9.js:129:18)
    at ChildProcess.emit (node:events:507:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Direct transcription error: Error: Python process exited with code 1
    at ChildProcess.<anonymous> (file:///app/build/server/chunks/jobQueue-CjBJp1X9.js:129:18)
    at ChildProcess.emit (node:events:507:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
[Hooks] Incoming request: {
  path: '/api/audio-files',
  method: 'GET',
  origin: null,
  host: '192.168.1.192:3000',
  referer: 'http://192.168.1.192:3000/'
}
[Hooks] Request origin: null

```

My GPU is using the latest nvidia driver. I am using the GPU fine in other containers (within Proxmox), and Ollama itself can use the GPU as expected so I'd imagine this is an issue with either Whisper, or my GPU being unsuported.

Nvidia-smi:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off |   00000000:26:00.0  On |                  N/A |
|  0%   29C    P8            N/A  /   90W |       5MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

My GPU is a 1050ti with the latest release drivers (not beta).

Cheers!
